### ISSUE TITLE
Remove Parameterless Constructors

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/task-router-servlets#6]
@EliuX Out of curiosity, why do you have private constructors?

If they are required, the the compiler will create public parameterless constructors for you.

Please take a look at:

- https://github.com/TwilioDevEd/task-router-servlets/blob/b5f9cc37e05ce95a1798c7ef49669f5154865f50/src/main/java/com/twilio/taskrouter/domain/model/MissedCall.java#L30-L31
- https://github.com/TwilioDevEd/task-router-servlets/blob/master/src/main/java/com/twilio/taskrouter/domain/model/PhoneNumber.java#L21-L22

**Comment by EliuX** [comment]
The default private constructor is because:

1. We need a default constructor for all JPA entities
1. We don't want the coder to create the JPA entity without specifying the required parameters. Therefore we need a second public constructor with all required params

[Here](http://stackoverflow.com/questions/6033905/create-the-perfect-jpa-entity) is a good explanation about it.

**Comment by acamino** [comment]
Thanks @EliuX, this is a really good explanation about why we **must** have a parameterless (_no-arg_) constructor. The link you provided is really useful.

My original question was:
> Out of curiosity, why do you have **private** constructors?

The private constructors are not used at all. Keep in mind the private constructor is not accessible outside the scope of the class.

`MissedCall` and `PhoneNumber` are working because if you don't define a explicitly a constructor for a class, a default _public_ parameterless constructor is automatically created by the compiler. This constructor satisfies the requirement "The no-arg constructor **must be public or protected**".

Would you mind removing the unused code please? Unless you have a strong reason to keep it that way.

**Comment by EliuX** [comment]
What i ment to say is that it needs a default constructor. If i have another one, the default one wont be implied, so it needs to be declared. After pairing a bit with @mcelicalderon we decided to make it `public` to be more JPA compliant, but its needed, i tried otherwise and didn't worked.

**Comment by mcelicalderon** [comment]
Yes, if you create a constructor with parameter you do need to create the default parameterless constructor. But it needs to be public or package-private (as protected), not just private as it was

**Comment by acamino** [comment]
Thanks guys!
