### ISSUE TITLE
Find Meaningful Names for Params

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/task-router-servlets#7]
@EliuX I think the facade abstraction fits really good in this implementation. Good work!

What do you think about introducing more meaningful names for params.
https://github.com/TwilioDevEd/task-router-servlets/blob/master/src/main/java/com/twilio/taskrouter/domain/model/WorkspaceFacade.java#L58

```java
  public Worker addWorker(Map<String, String> parameters) {
    try {

      return workspace.createWorker(parameters);
    } catch (TwilioRestException e) {
      throw new TaskRouterException(String.format(
        "Error while adding the worker '%s' to workspace: %s",
        parameters.get("FriendlyName"), e.getMessage()));
    }
  }
```

By definition anything you pass to the method `addWorker` is a _formal parameter_ a.k.a _parameter_, so naming a parameter as parameter doesn't add any semantic value.

Using something more meaningful like `worker` would increase the understanding of the method.

```java
  public Worker addWorker(Map<String, String> worker) {
    try {

      return workspace.createWorker(worker);
    } catch (TwilioRestException e) {
      throw new TaskRouterException(String.format(
        "Error while adding the worker '%s' to workspace: %s",
        worker.get("FriendlyName"), e.getMessage()));
    }
  }
```

What do you think?

**Comment by EliuX** [comment]
Maybe `workerParams` would be good, so by autocompletion it would fit with client code of the function without matching the wrong ones. But `worker` without looking its type may give an idea we are handling a `Worker` instance.
So i will rename the parameter to `workerParams` which is a middle ground.

**Comment by acamino** [comment]
Thanks @EliuX. `workerParams` fits perfectly in this method. 👍
